import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  Download,
  FilePlus,
  FileText,
  Plus,
  Search,
  Trash2,
} from "lucide-react";

import { invoicesQuery } from "@/lib/finance/queries";
import { useCreateInvoice, useUpdateInvoice } from "@/lib/finance/mutations";
import type { FinanceView } from "@/lib/finance/views";
import type { Invoice, InvoiceLineItem } from "@/lib/finance/types";
import { PanelCard, QueryState, SectionShell, StatCard, StatGrid, StatusBadge } from "@/components/finance/ui-kit";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { downloadCsv, formatCurrency, formatDate } from "@/lib/finance/format";

const VIEW_META: Record<
  string,
  { title: string; description: string; filters?: { docType?: Invoice["doc_type"]; clientType?: string; autoGenerated?: boolean } }
> = {
  invoice_generate: { title: "Generate Invoice", description: "Create a new invoice, tax invoice, credit or debit note" },
  invoice_auto: { title: "Auto Invoice", description: "Invoices generated automatically by the billing engine", filters: { autoGenerated: true } },
  invoice_franchise: { title: "Franchise Invoices", description: "Invoices billed to franchise partners", filters: { clientType: "franchise" } },
  invoice_reseller: { title: "Reseller Invoices", description: "Invoices billed to resellers", filters: { clientType: "reseller" } },
  invoice_tax: { title: "Tax Invoices", description: "GST/tax invoices issued", filters: { docType: "tax_invoice" } },
  invoice_credit_note: { title: "Credit Notes", description: "Credit notes issued against invoices", filters: { docType: "credit_note" } },
  invoice_debit_note: { title: "Debit Notes", description: "Debit notes issued against invoices", filters: { docType: "debit_note" } },
};

const STATUS_FLOW: Record<string, Invoice["status"][]> = {
  draft: ["unpaid", "cancelled"],
  sent: ["paid", "overdue", "cancelled"],
  overdue: ["paid", "cancelled"],
  paid: [],
  cancelled: [],
};

function emptyLineItem(): InvoiceLineItem {
  return { description: "", qty: 1, rate: 0 };
}

function InvoiceGenerateForm() {
  const createInvoice = useCreateInvoice();
  const [clientName, setClientName] = useState("");
  const [clientType, setClientType] = useState("user");
  const [docType, setDocType] = useState<Invoice["doc_type"]>("invoice");
  const [gstNumber, setGstNumber] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [taxPercent, setTaxPercent] = useState(18);
  const [lineItems, setLineItems] = useState<InvoiceLineItem[]>([emptyLineItem()]);

  const subtotal = useMemo(
    () => lineItems.reduce((sum, li) => sum + Number(li.qty || 0) * Number(li.rate || 0), 0),
    [lineItems],
  );
  const taxAmount = subtotal * (taxPercent / 100);
  const total = subtotal + taxAmount;

  const updateLineItem = (idx: number, patch: Partial<InvoiceLineItem>) => {
    setLineItems((prev) => prev.map((li, i) => (i === idx ? { ...li, ...patch } : li)));
  };

  const canSubmit = clientName.trim() && dueDate && lineItems.every((li) => li.description.trim() && li.qty > 0);

  const handleSubmit = () => {
    if (!canSubmit) return;
    createInvoice.mutate(
      {
        clientName: clientName.trim(),
        clientType,
        docType,
        gstNumber: gstNumber.trim() || undefined,
        dueDate,
        taxPercent,
        lineItems,
        actor: "finance_manager",
      },
      {
        onSuccess: () => {
          setClientName("");
          setGstNumber("");
          setDueDate("");
          setTaxPercent(18);
          setLineItems([emptyLineItem()]);
        },
      },
    );
  };

  return (
    <PanelCard title="Create New Invoice">
      <div className="space-y-4">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <div className="space-y-1.5">
            <Label>Client Name</Label>
            <Input value={clientName} onChange={(e) => setClientName(e.target.value)} placeholder="Enter client name" />
          </div>
          <div className="space-y-1.5">
            <Label>Client Type</Label>
            <Select value={clientType} onValueChange={setClientType}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="franchise">Franchise</SelectItem>
                <SelectItem value="reseller">Reseller</SelectItem>
                <SelectItem value="user">User</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1.5">
            <Label>Document Type</Label>
            <Select value={docType} onValueChange={(v) => setDocType(v as Invoice["doc_type"])}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="invoice">Invoice</SelectItem>
                <SelectItem value="tax_invoice">Tax Invoice</SelectItem>
                <SelectItem value="credit_note">Credit Note</SelectItem>
                <SelectItem value="debit_note">Debit Note</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1.5">
            <Label>GST Number</Label>
            <Input value={gstNumber} onChange={(e) => setGstNumber(e.target.value)} placeholder="Optional" />
          </div>
          <div className="space-y-1.5">
            <Label>Due Date</Label>
            <Input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} />
          </div>
          <div className="space-y-1.5">
            <Label>Tax %</Label>
            <Input
              type="number"
              min={0}
              max={100}
              value={taxPercent}
              onChange={(e) => setTaxPercent(Number(e.target.value))}
            />
          </div>
        </div>

        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <Label>Line Items</Label>
            <Button variant="outline" size="sm" className="gap-1" onClick={() => setLineItems((prev) => [...prev, emptyLineItem()])}>
              <Plus className="h-3.5 w-3.5" />
              Add Item
            </Button>
          </div>
          <div className="space-y-2">
            {lineItems.map((li, idx) => (
              <div key={idx} className="grid grid-cols-1 gap-2 sm:grid-cols-[1fr_100px_120px_120px_36px] items-center">
                <Input
                  placeholder="Description"
                  value={li.description}
                  onChange={(e) => updateLineItem(idx, { description: e.target.value })}
                />
                <Input
                  type="number"
                  min={1}
                  placeholder="Qty"
                  value={li.qty}
                  onChange={(e) => updateLineItem(idx, { qty: Number(e.target.value) })}
                />
                <Input
                  type="number"
                  min={0}
                  placeholder="Rate"
                  value={li.rate}
                  onChange={(e) => updateLineItem(idx, { rate: Number(e.target.value) })}
                />
                <p className="text-sm font-medium text-foreground">{formatCurrency(li.qty * li.rate)}</p>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-8 w-8 p-0 text-destructive"
                  disabled={lineItems.length === 1}
                  onClick={() => setLineItems((prev) => prev.filter((_, i) => i !== idx))}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            ))}
          </div>
        </div>

        <div className="flex flex-col items-end gap-1 border-t border-border pt-3 text-sm">
          <p className="text-muted-foreground">Subtotal: <span className="font-medium text-foreground">{formatCurrency(subtotal)}</span></p>
          <p className="text-muted-foreground">Tax ({taxPercent}%): <span className="font-medium text-foreground">{formatCurrency(taxAmount)}</span></p>
          <p className="text-base font-semibold text-foreground">Total: {formatCurrency(total)}</p>
        </div>

        <Button className="gap-2" disabled={!canSubmit || createInvoice.isPending} onClick={handleSubmit}>
          <FilePlus className="h-4 w-4" />
          Generate Invoice
        </Button>
      </div>
    </PanelCard>
  );
}

function InvoiceListView({ view }: { view: FinanceView }) {
  const meta = VIEW_META[view] ?? VIEW_META['invoice_franchise']!;
  const invoicesState = useQuery(invoicesQuery(meta.filters));
  const updateInvoice = useUpdateInvoice();
  const [search, setSearch] = useState("");

  const rows = invoicesState.data ?? [];
  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return rows;
    return rows.filter(
      (r) => r.invoice_no.toLowerCase().includes(q) || r.client_name.toLowerCase().includes(q),
    );
  }, [rows, search]);

  const stats = useMemo(() => {
    const total = rows.reduce((sum, r) => sum + Number(r.total), 0);
    const paid = rows.filter((r) => r.status === "paid").reduce((sum, r) => sum + Number(r.total), 0);
    const pending = rows.filter((r) => r.status === "unpaid").reduce((sum, r) => sum + Number(r.total), 0);
    const overdue = rows.filter((r) => r.status === "overdue").reduce((sum, r) => sum + Number(r.total), 0);
    return { total, paid, pending, overdue };
  }, [rows]);

  const handleExport = () => {
    if (!filtered.length) return;
    downloadCsv(`${view}.csv`, filtered.map((r) => ({
      invoice_no: r.invoice_no,
      client_name: r.client_name,
      client_type: r.client_type,
      doc_type: r.doc_type,
      subtotal: r.subtotal,
      tax_amount: r.tax_amount,
      total: r.total,
      status: r.status,
      issue_date: r.issue_date,
      due_date: r.due_date,
    })));
  };

  return (
    <div className="space-y-6">
      <StatGrid>
        <StatCard label="Total Invoiced" value={formatCurrency(stats.total)} tone="default" />
        <StatCard label="Paid" value={formatCurrency(stats.paid)} tone="success" />
        <StatCard label="Pending" value={formatCurrency(stats.pending)} tone="warning" />
        <StatCard label="Overdue" value={formatCurrency(stats.overdue)} tone="danger" />
      </StatGrid>

      <div className="flex flex-wrap gap-3">
        <div className="relative flex-1 min-w-[220px]">
          <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            className="pl-9"
            placeholder="Search by invoice number or client..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <Button variant="outline" className="gap-2" onClick={handleExport}>
          <Download className="h-4 w-4" />
          Export CSV
        </Button>
      </div>

      <PanelCard title="Invoices">
        <QueryState isLoading={invoicesState.isLoading} error={invoicesState.error} isEmpty={filtered.length === 0} emptyLabel="No invoices found">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs text-muted-foreground border-b border-border">
                  <th className="pb-2 font-medium">Invoice No</th>
                  <th className="pb-2 font-medium">Client</th>
                  <th className="pb-2 font-medium">Type</th>
                  <th className="pb-2 font-medium">Total</th>
                  <th className="pb-2 font-medium">Issue Date</th>
                  <th className="pb-2 font-medium">Due Date</th>
                  <th className="pb-2 font-medium">Status</th>
                  <th className="pb-2 font-medium">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {filtered.map((invoice) => {
                  const nextStatuses = STATUS_FLOW[invoice.status] ?? [];
                  return (
                    <tr key={invoice.id}>
                      <td className="py-2 font-mono text-primary">{invoice.invoice_no}</td>
                      <td className="py-2 font-medium text-foreground">{invoice.client_name}</td>
                      <td className="py-2">
                        <span className="text-xs capitalize text-muted-foreground">{invoice.doc_type.replace(/_/g, " ")}</span>
                      </td>
                      <td className="py-2 font-semibold text-foreground">{formatCurrency(invoice.total)}</td>
                      <td className="py-2 text-muted-foreground">{formatDate(invoice.issue_date)}</td>
                      <td className="py-2 text-muted-foreground">{formatDate(invoice.due_date)}</td>
                      <td className="py-2">
                        <StatusBadge status={invoice.status} />
                      </td>
                      <td className="py-2">
                        <div className="flex flex-wrap gap-1">
                          {nextStatuses.map((s) => (
                            <Button
                              key={s}
                              variant="outline"
                              size="sm"
                              className="h-7 px-2 text-xs capitalize"
                              disabled={updateInvoice.isPending}
                              onClick={() =>
                                updateInvoice.mutate({ id: invoice.id, status: s, actor: "finance_manager" })
                              }
                            >
                              {s}
                            </Button>
                          ))}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </QueryState>
      </PanelCard>
    </div>
  );
}

export default function InvoiceSections({ view }: { view: FinanceView }) {
  const meta = VIEW_META[view] ?? VIEW_META['invoice_franchise']!;

  return (
    <SectionShell title={meta.title} description={meta.description} icon={FileText}>
      {view === "invoice_generate" ? (
        <div className="space-y-6">
          <InvoiceGenerateForm />
          <InvoiceListView view={view} />
        </div>
      ) : (
        <InvoiceListView view={view} />
      )}
    </SectionShell>
  );
}
