import { queryOptions } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type {
  ActivityHeat,
  AiApiUsage,
  Approval,
  AuditLog,
  Commission,
  DailyMetric,
  Expense,
  FinanceAlert,
  FinanceTransaction,
  FraudAlert,
  Gateway,
  Invoice,
  Payout,
  Plan,
  Refund,
  Subscription,
  TaxRecord,
  Wallet,
  WalletTransaction,
} from "./types";

async function unwrap<T>(promise: PromiseLike<{ data: T | null; error: { message: string } | null }>) {
  const { data, error } = await promise;
  if (error) throw new Error(error.message);
  return (data ?? []) as T;
}

export const financeKeys = {
  all: ["finance"] as const,
  entity: (name: string, params?: unknown) =>
    params === undefined ? (["finance", name] as const) : (["finance", name, params] as const),
};

export const walletsQuery = (ownerType?: Wallet["owner_type"]) =>
  queryOptions({
    queryKey: financeKeys.entity("wallets", ownerType ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_wallets").select("*").order("balance", { ascending: false });
      if (ownerType) q = q.eq("owner_type", ownerType);
      return unwrap<Wallet[]>(q);
    },
  });

export const walletTransactionsQuery = (entryType?: WalletTransaction["entry_type"]) =>
  queryOptions({
    queryKey: financeKeys.entity("wallet-transactions", entryType ?? "all"),
    queryFn: () => {
      let q = supabase
        .from("finance_wallet_transactions")
        .select("*, finance_wallets(owner_name, owner_code, owner_type)")
        .order("created_at", { ascending: false })
        .limit(200);
      if (entryType) q = q.eq("entry_type", entryType);
      return unwrap<(WalletTransaction & { finance_wallets: Pick<Wallet, "owner_name" | "owner_code" | "owner_type"> | null })[]>(q);
    },
  });

export const transactionsQuery = (filters?: {
  direction?: FinanceTransaction["direction"];
  status?: FinanceTransaction["status"];
  gateway?: string;
  limit?: number;
}) =>
  queryOptions({
    queryKey: financeKeys.entity("transactions", filters ?? {}),
    queryFn: () => {
      let q = supabase
        .from("finance_transactions")
        .select("*")
        .order("occurred_at", { ascending: false })
        .limit(filters?.limit ?? 150);
      if (filters?.direction) q = q.eq("direction", filters.direction);
      if (filters?.status) q = q.eq("status", filters.status);
      if (filters?.gateway) q = q.eq("gateway", filters.gateway);
      return unwrap<FinanceTransaction[]>(q);
    },
  });

export const gatewaysQuery = () =>
  queryOptions({
    queryKey: financeKeys.entity("gateways"),
    queryFn: () => unwrap<Gateway[]>(supabase.from("finance_gateways").select("*").order("monthly_volume", { ascending: false })),
  });

export const invoicesQuery = (filters?: { docType?: Invoice["doc_type"]; status?: Invoice["status"]; clientType?: string; autoGenerated?: boolean }) =>
  queryOptions({
    queryKey: financeKeys.entity("invoices", filters ?? {}),
    queryFn: () => {
      let q = supabase.from("finance_invoices").select("*").order("issue_date", { ascending: false }).limit(200);
      if (filters?.docType) q = q.eq("doc_type", filters.docType);
      if (filters?.status) q = q.eq("status", filters.status);
      if (filters?.clientType) q = q.eq("client_type", filters.clientType);
      if (filters?.autoGenerated !== undefined) q = q.eq("auto_generated", filters.autoGenerated);
      return unwrap<Invoice[]>(q);
    },
  });

export const plansQuery = () =>
  queryOptions({
    queryKey: financeKeys.entity("plans"),
    queryFn: () => unwrap<Plan[]>(supabase.from("finance_plans").select("*").order("price")),
  });

export const subscriptionsQuery = (status?: Subscription["status"]) =>
  queryOptions({
    queryKey: financeKeys.entity("subscriptions", status ?? "all"),
    queryFn: () => {
      let q = supabase
        .from("finance_subscriptions")
        .select("*, finance_plans(*)")
        .order("expires_at", { ascending: true })
        .limit(200);
      if (status) q = q.eq("status", status);
      return unwrap<Subscription[]>(q);
    },
  });

export const commissionsQuery = (partnerType?: Commission["partner_type"]) =>
  queryOptions({
    queryKey: financeKeys.entity("commissions", partnerType ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_commissions").select("*").order("created_at", { ascending: false }).limit(200);
      if (partnerType) q = q.eq("partner_type", partnerType);
      return unwrap<Commission[]>(q);
    },
  });

export const payoutsQuery = (status?: Payout["status"]) =>
  queryOptions({
    queryKey: financeKeys.entity("payouts", status ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_payouts").select("*").order("requested_at", { ascending: false }).limit(200);
      if (status) q = q.eq("status", status);
      return unwrap<Payout[]>(q);
    },
  });

export const expensesQuery = (category?: Expense["category"]) =>
  queryOptions({
    queryKey: financeKeys.entity("expenses", category ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_expenses").select("*").order("expense_date", { ascending: false }).limit(200);
      if (category) q = q.eq("category", category);
      return unwrap<Expense[]>(q);
    },
  });

export const aiUsageQuery = (providerFilter?: "ai" | "api") =>
  queryOptions({
    queryKey: financeKeys.entity("ai-usage", providerFilter ?? "all"),
    queryFn: () =>
      unwrap<AiApiUsage[]>(
        supabase.from("finance_ai_api_usage").select("*").order("usage_date", { ascending: false }).limit(400),
      ),
  });

export const refundsQuery = (status?: Refund["status"]) =>
  queryOptions({
    queryKey: financeKeys.entity("refunds", status ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_refunds").select("*").order("requested_at", { ascending: false }).limit(200);
      if (status) q = q.eq("status", status);
      return unwrap<Refund[]>(q);
    },
  });

export const taxRecordsQuery = (taxType?: TaxRecord["tax_type"]) =>
  queryOptions({
    queryKey: financeKeys.entity("tax", taxType ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_tax_records").select("*").order("due_date", { ascending: false });
      if (taxType) q = q.eq("tax_type", taxType);
      return unwrap<TaxRecord[]>(q);
    },
  });

export const alertsQuery = () =>
  queryOptions({
    queryKey: financeKeys.entity("alerts"),
    queryFn: () => unwrap<FinanceAlert[]>(supabase.from("finance_alerts").select("*").order("created_at", { ascending: false })),
  });

export const approvalsQuery = (status?: Approval["status"]) =>
  queryOptions({
    queryKey: financeKeys.entity("approvals", status ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_approvals").select("*").order("created_at", { ascending: false });
      if (status) q = q.eq("status", status);
      return unwrap<Approval[]>(q);
    },
  });

export const auditLogsQuery = (severity?: AuditLog["severity"]) =>
  queryOptions({
    queryKey: financeKeys.entity("audit-logs", severity ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_audit_logs").select("*").order("created_at", { ascending: false }).limit(200);
      if (severity) q = q.eq("severity", severity);
      return unwrap<AuditLog[]>(q);
    },
  });

export const fraudAlertsQuery = (status?: FraudAlert["status"]) =>
  queryOptions({
    queryKey: financeKeys.entity("fraud", status ?? "all"),
    queryFn: () => {
      let q = supabase.from("finance_fraud_alerts").select("*").order("detected_at", { ascending: false });
      if (status) q = q.eq("status", status);
      return unwrap<FraudAlert[]>(q);
    },
  });

export const dailyMetricsQuery = (days = 180) =>
  queryOptions({
    queryKey: financeKeys.entity("daily-metrics", days),
    queryFn: () =>
      unwrap<DailyMetric[]>(
        supabase.from("finance_daily_metrics").select("*").order("metric_date", { ascending: false }).limit(days),
      ),
  });

export const activityHeatQuery = () =>
  queryOptions({
    queryKey: financeKeys.entity("activity-heat"),
    queryFn: () =>
      unwrap<ActivityHeat[]>(
        supabase
          .from("finance_activity_heat")
          .select("*")
          .order("activity_date", { ascending: false })
          .order("hour_slot", { ascending: true })
          .limit(672),
      ),
  });
